// PSY ANTHEM - scripts/validate-in-daw.ts
// Produces a DAW-validation bundle: the 10 golden MIDIs plus a checklist.
// Run: bun run scripts/validate-in-daw.ts
// Then import daw-validation/*.mid into your DAW (see docs/DAW-INTEGRATION.md).
import { GOLDEN_SPECS } from './generate-golden';
import { createAnthemEngine } from '../src/index';
import { writeMidiFile } from '../src/export';

const OUT_DIR = 'daw-validation';

const CHECKLIST = [
'# DAW Validation Checklist',
'',
'Generated by scripts/validate-in-daw.ts. Import every .mid in this folder.',
'',
'## Per-file checks',
'',
'- [ ] File imports without errors',
'- [ ] Tempo matches the stated BPM (check the transport after import)',
'- [ ] Time signature reads 4/4',
'- [ ] One track per voice (3 or 4 tracks depending on file)',
'- [ ] Program changes present: ch1=0, ch2=80, ch3=24, ch4=33',
'- [ ] Track lengths match the bar count (bars x 4 beats)',
'- [ ] No stuck notes (every note-on has a matching note-off)',
'- [ ] Notes sit in a sensible range (lead around C4-C6, bass around C2-G3)',
'',
'## Musical checks (subjective)',
'',
'- [ ] The melody has a recognizable repeating motif',
'- [ ] There is a clear build and release matching the file description',
'- [ ] Bass follows the chord roots',
'- [ ] Assign your own instruments - does it feel like a playable arrangement?',
'',
'## Known-good reference',
'',
'Every file here is byte-identical to golden-midi/ (regenerated fresh).',
'If your DAW reports different content, it is a DAW interpretation issue,',
'not a file issue - see docs/DAW-INTEGRATION.md for per-DAW notes.',
].join('\n');

function main(): void {
  console.log('=== PSY ANTHEM - DAW validation bundle ===');
  let total = 0;
  for (const spec of GOLDEN_SPECS) {
    const out = createAnthemEngine(spec.config).generate();
    if (!out) throw new Error('generation failed for ' + spec.file);
    const path = OUT_DIR + '/' + spec.file;
    const bytes = writeMidiFile(out, path, { bpm: spec.config.bpm ?? 140 });
    total += bytes;
    console.log(spec.file.padEnd(32), String(bytes).padStart(6) + ' bytes', spec.description);
  }
  writeMidiFile; // keep import explicit for clarity
  const fs = require('node:fs') as typeof import('node:fs');
  fs.writeFileSync(OUT_DIR + '/CHECKLIST.md', CHECKLIST);
  console.log('');
  console.log('wrote 10 MIDI files + CHECKLIST.md to ' + OUT_DIR + '/ (' + total + ' bytes of MIDI)');
  console.log('next: import into your DAW and work through daw-validation/CHECKLIST.md');
}

main();
